defaults:
  - _self_
  - experiments: base 

model:
  pretrained: "facebook/sam-vit-huge"
  use_lora: true
  use_ia3: true             # if true, use ia3 even if lora true
  freeze_base: true
  lora_config:
    r: 32
    lora_alpha: 32
    target_modules: ["q_proj", "k_proj", "v_proj", "out_proj"]
    lora_dropout: 0.1
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
  ia3_config:
    target_modules: ["q_proj", "k_proj", "v_proj", "out_proj"]
    feedforward_modules: []  
    fan_in_fan_out: false
    init_ia3_weights: true
    task_type: "FEATURE_EXTRACTION"  

training:
  epochs: 1
  batch_size: 4
  lr: 1e-4
  warmup_steps: 200
  num_workers: 2
  log_interval: 10
  use_mask: true
  use_subset: false
  size_of_subset: 1
  train_val_split: 0.85
  seed: 228
  output_dir: "/home/dmatveev/workdir/rosneft_segmentation/models/try_5_box"

train_data:
  - type: "2D"
    seismic_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/Salt2d/seismic"
    label_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/Salt2d/label"
    shape: [224, 224]
    mask_dtype: "np.uint8"
    pad_size:
      height: 1024
      width: 1024

  - type: "2D"
    seismic_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/sabamrine/seismic"
    label_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/sabamrine/label"
    shape: [256, 256]
    mask_dtype: "np.uint8"
    pad_size:
      height: 1024
      width: 1024
      
  - type: "2D"
    seismic_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/paleokart/seismic"
    label_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/paleokart/label"
    shape: [256, 256]
    mask_dtype: "np.uint8"
    pad_size:
      height: 1024
      width: 1024

test_data:
  - name: "paleovres"
    type: "2D"
    seismic_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/from_rosneft/2d_paleovres/seismic"
    label_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/from_rosneft/2d_paleovres/label"
    shape: [401, 401]
    mask_dtype: "np.uint8"
    pad_size:
      height: 1024
      width: 1024
  - name: "rifs"
    type: "2D"
    seismic_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/from_rosneft/rifs/seismic"
    label_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/from_rosneft/rifs/label"
    shape: [301, 301]
    mask_dtype: "np.uint8"
    pad_size:
      height: 1024
      width: 1024

prompt:
  type: "bbox+points"           # "point", "circle", "bbox", "bbox+points"  # или "bbox+circles"
  num_points: 16
  num_circles: 5
  circle_mean_diameter: 5
  circle_diameter_delta: 1
  bbox_error: 0

clearml:
  project_name: "Rosneft segmentation"
  task_name: "Experiment 40|unfreeze encoder select best mask (channel), with 16 points| train on Salt2d, sabamrine | test paleovreses, rifs | 2 epoch, - steps warmup | 4 batch size | multimask_output=False"
