model:
  pretrained: "facebook/sam-vit-huge"
  use_lora: true
  freeze_base: false
  lora_config:
    r: 32
    lora_alpha: 32
    target_modules: ["q_proj", "k_proj", "v_proj", "out_proj"]
    lora_dropout: 0.1
    bias: "none"
    task_type: "FEATURE_EXTRACTION"

training:
  epochs: 1
  batch_size: 4
  lr: 1e-4
  num_workers: 2
  log_interval: 10
  use_mask: true
  use_subset: true
  size_of_subset: 10
  train_val_split: 0.8

train_data:
  - type: "2D"
    seismic_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/Salt2d/seismic"
    label_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/Salt2d/label"
    shape: [224, 224]
    mask_dtype: "np.uint8"
    pad_size:
      height: 1024
      width: 1024

  - type: "2D"
    seismic_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/sabamrine/seismic"
    label_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/sabamrine/label"
    shape: [256, 256]
    mask_dtype: "np.uint8"
    pad_size:
      height: 1024
      width: 1024

test_data:
  type: "2D"
  seismic_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/from_rosneft/2d_paleovres/seismic"
  label_dir: "/home/dmatveev/workdir/rosneft_segmentation/data/from_rosneft/2d_paleovres/label"
  shape: [401, 401]
  mask_dtype: "np.uint8"
  pad_size:
    height: 1024
    width: 1024

clearml:
  project_name: "Rosneft segmentation"
  task_name: "Experiment 14| select best mask (channel), with centre point | train on Salt2d, sabamrine | test 2d_paleovres"
